### ISSUE TITLE
triples extraction question?

### ISSUE THREAD

**Issue by chenhch8** [bekou/multihead_joint_entity_relation_extraction#1]
Hey, can this program be directly used to extract triples for a given raw sentence? It seems that in you test/dev file, the relation between entities must be known first. So it cannot directly deal with a raw sentence.

**Comment by bekou** [comment]
Hi @chenhch8 . The relation extraction module can deal with raw sentences. However, the relations should be known since the training should be performed on a known set of relations. The same holds for the entities (i.e., the types of the entities should be also known for the training set). For the test/dev sets, the relations are there just for evaluation purposes. Our relation extractor could be used without the named entity module. For this you should deactivate the first objective and the label embeddings which are propagated from the named entity recognition to the relation extraction module.
