### ISSUE TITLE
ACE 04 Train / dev splits

### ISSUE THREAD

**Issue by btaille** [bekou/multihead_joint_entity_relation_extraction#12]
Hello and thank you for your work,
 
In your article you say that you compute a random dev set of 15% of the data for each fold of ACE04. Could you release the list of documents selected for each fold? 
Additionally, the datasets statistics such as number of sentences, mentions and relations could be helpful to ensure that the experimental setting is exactly reproduced.

**Comment by bekou** [comment]
Hi, the train and test splits are the same as described in the work of [Miwa and Bansal](https://github.com/tticoin/LSTM-ER/tree/master/data/ace2004). For the train and dev sets, I think that it doesn't matter that much the way that you do the splitting (i.e., that is why I split a random dev set) since in any case, you will train on the whole train+dev set to obtain your final model for the fold.

**Comment by hi-wangyan** [comment]
Hi, can you sent me the dataset of ACE04,Thank you! @bekou
