### ISSUE TITLE
what's the difference between your multihead selection and table filling methods?

### ISSUE THREAD

**Issue by edfall** [bekou/multihead_joint_entity_relation_extraction#14]
the table filling methods in  https://www.aclweb.org/anthology/C16-1239:
![image](https://user-images.githubusercontent.com/12717769/58451366-c76c4980-8145-11e9-8fac-3d4a88d805b3.png)

and your multihead selection:
https://github.com/bekou/multihead_joint_entity_relation_extraction/blob/9fcabf5d940838f764e611728e03597be487d43f/tf_utils.py#L301-L302

is so similar, I get puzzled for that I can't see any difference between multihead selection and table filling methods.

@bekou

**Comment by bekou** [comment]
Hi, the goal for this task is indeed to predict the entries for such a table. However, there are various approaches that you can do it. I selected to do it with our multi-head selection method. Some differences compared to the two approaches. We : (i) train our model by modeling all the entities and the relations of the sentence at once instead of replicating the context around the word pairs, (ii) use a quadratic matrix that has as columns the number of tokens multiplied with the number of possible relations, (iii) predict the head for each token using the methods described in our work, and (iv) use the proposed architecture of the (entity and relation extraction) network which is different compared to the one that is used in this work. 

For discussing the methods (and not the code), I prefer to do it over mail instead of opening a github issue for that.
