### ISSUE TITLE
Are these the hyperparameters from the articles ?

### ISSUE THREAD

**Issue by btaille** [bekou/multihead_joint_entity_relation_extraction#15]
Thanks again for your great work and especially for structuring a messy state-of-the-art.

Are the hyperparameters in the `configs/` folder the ones you used to obtain scores reported in your articles? In particular, I think you don't mention using a multi-layer BiLSTM in your first article.

I fail to replicate your result without adversarial training on CoNLL04 when running your code.
The gap is quite significant since I obtain 82.2 NER / 58.4 RE against the reported 83.9 / 62.0.
I use `train_eval.py` with the best epoch from `train_es.py`.

Do you know what could cause that difference?

**Comment by bekou** [comment]
Hi @btaille and thanks for your kind words. Indeed, the hyperparameters used in the configuration files are the ones used also in our papers.  Specifically for this setting, using the provided code, I obtain 84.12 NER / 61.48 RE. I suspect that the change you have in performance might be due to different packages used or operating system (i.e., we used Ubuntu 16.04). You can find the requirements in our github codebase. We used multi-layer BiLSTMs in all of the experiments. Indeed the proper way is to obtain the best epoch through the train_es.py and use it for the train_eval.py (i.e., the code will do that for you).
