### ISSUE TITLE
Why is the model worse after adding the adversarial training in CoNLL dataset?

### ISSUE THREAD

**Issue by jcsyl** [bekou/multihead_joint_entity_relation_extraction#2]

**Comment by bekou** [comment]
Hi @jcsyl,

There is an increase using the adversarial training for both the bio and the ec configurations in all of the datasets (also in the CoNLL). 
Do you point to the required files for each configuration? 
There is one configuration file per setting. 
For instance, when you want to report results using the bio scheme, you use the bio_config file in the run.sh, while when you want to use the bio scheme with adversarial training
you have to point the run.sh to the bio_config_adv configuration file. 
For the ec configuration with and without adversarial training, you should point to the ec_config and ec_config_adv files, respectively.

Note that scores may be inconsistent due to different environments.
